apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdb
  labels:
    app: springdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springdb
  template:
    metadata:
      labels:
        app: springdb
    spec:
      containers:
      - name: springdb
        image: mysql:8.0
        ports:
        - containerPort: 3306
        command: ["/bin/sh", "-ec", "while :; do echo 'Hello'; sleep 5; done"]
        env:
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springdb-secret
              key: root-password
        - name: DB_DATABASE
          value: "spring"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: springdb-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: springdb-secret
              key: password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: springdb
  labels:
    app: springdb
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: springdb
  clusterIP: None
